[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "robocompdsl"
version = "2026.2.20"
description = "Robocompdsl application"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GPL V3"}
authors = [
    {name = "Esteban Martinena", email = "emartinena@unex.es"}, 
    {name = "Alejandro Torrejón", email = "atorrejon@unex.es"}, 
]

dependencies = [
    "PySide6>=6.9.0",
    "zeroc-ice==3.7.10.1",
    "toml==0.10.2",
    "typer>=0.4.1",
    "docker>=7.1.0",
    "pyyaml>=6.0.2",
    "prompt_toolkit>=3.0.48",
    "ruamel.yaml>=0.18.6",
    "rich>=13.9.4",
    "termcolor>=2.5.0",
    "argcomplete>=3.5.1",
    "pyparsing>=3.2.3",
    "setproctitle>=1.3.4",
]

[project.scripts]
robocomp = "robocomp.main:app"
rcbuild = "rcbuild.main:app"
rccd = "rccd.main:app"
rcconfig = "rcconfig.main:app"
rcdocker = "rcdocker.main:app"
rcportchecker = "rcportchecker.main:app"
rcrun = "rcrun.main:app"
rcworkspace = "rcworkspace.main:app"
robocompdsl = "robocompdsl.main:app"

[tool.setuptools]
packages.find = {where = ["src"]}
py-modules = ["cli_helpers", "logging_helpers"]
[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
"robocompdsl" = [
    "common/*.py",
    "common/**/*.py",
    "templates/**/*",
    "dsl_parsers/*.py",
    "dsl_parsers/**/*.py",
    "*.md",
]